## UNIVARIATE FEATURE SELECTION

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [2]:
df = pd.read_csv(r"C:\Users\mobin\DATASIENCE\feature engineering\pima-indians-diabetes.data.csv")

In [3]:
df.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [4]:
X = df.drop('class' , axis = 1)
Y = df.iloc[: , -1]

In [5]:
Y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: class, Length: 768, dtype: int64

In [6]:
X.head()

preg  plas  pres  skin  test  mass   pedi  age
0     6   148    72    35     0  33.6  0.627   50
1     1    85    66    29     0  26.6  0.351   31
2     8   183    64     0     0  23.3  0.672   32
3     1    89    66    23    94  28.1  0.167   21
4     0   137    40    35   168  43.1  2.288   33

In [11]:
test = SelectKBest(score_func=f_classif, k = 5 )
fit = test.fit(X,Y)
features = fit.transform(X)
features

array([[  6.   , 148.   ,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  30.4  ,   0.315,  23.   ]])

In [12]:
fit.scores_

array([ 39.67022739, 213.16175218,   3.2569504 ,   4.30438091,
        13.28110753,  71.7720721 ,  23.8713002 ,  46.14061124])

In [14]:
fit.get_feature_names_out()

array(['preg', 'plas', 'mass', 'pedi', 'age'], dtype=object)

In [19]:
dataframe = pd.DataFrame(fit.scores_).T
dataframe.columns = X.columns
dataframe

preg        plas     pres      skin       test       mass     pedi  \
0  39.670227  213.161752  3.25695  4.304381  13.281108  71.772072  23.8713   

         age  
0  46.140611

## RECURSIVE FEATURE ELIMINATION

In [30]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

X = df.drop('class' , axis = 1)
Y = df.iloc[: , -1]

model = LogisticRegression()
rfe = RFE(estimator = model, n_features_to_select = 6)
rfe_fit = rfe.fit(X,Y)


C:\Users\mobin\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\mobin\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [33]:
rfe_fit.n_features_

6

In [34]:
rfe_fit.support_

array([ True,  True,  True, False, False,  True,  True,  True])

In [35]:
rfe_fit.get_feature_names_out()

array(['preg', 'plas', 'pres', 'mass', 'pedi', 'age'], dtype=object)

In [36]:
rfe_fit.ranking_

array([1, 1, 1, 2, 3, 1, 1, 1])